# Generated by Django 5.1 on 2024-08-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_hashtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="posts.hashtag", verbose_name="해시태그 목록"
            ),
        ),
    ]
