# Generated by Django 5.1 on 2024-08-28 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_alter_movies_post_famousline"),
        ("posts", "0004_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="movies",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.movies_post",
                verbose_name="영화",
            ),
            preserve_default=False,
        ),
    ]
