# Generated by Django 5.1 on 2024-08-27 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                related_name="followers",
                through="users.Relationship",
                to=settings.AUTH_USER_MODEL,
                verbose_name="팔로우 중인 사용자들",
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_relationships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="팔로우를 요청한 사용자",
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower_relationships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="팔로우 요청받은 사용자",
            ),
        ),
    ]
