# Generated by Django 5.1 on 2024-08-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="movies_post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="영화제목")),
                ("image", models.ImageField(upload_to="", verbose_name="포스터")),
                ("storyline", models.TextField(verbose_name="줄거리")),
                (
                    "runningtime",
                    models.IntegerField(default=0, verbose_name="러닝타임"),
                ),
                ("gnere", models.CharField(max_length=10, verbose_name="장르")),
                ("director", models.CharField(max_length=20, verbose_name="감독")),
                ("year", models.CharField(max_length=10, verbose_name="제작년도")),
                ("agelimit", models.CharField(max_length=10, verbose_name="연령제한")),
                ("Country", models.CharField(max_length=10, verbose_name="국가")),
                ("famousline", models.TextField(blank=True, verbose_name="명대사")),
            ],
        ),
    ]
