# Generated by Django 5.1 on 2024-08-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies_post",
            name="image",
            field=models.ImageField(upload_to="post", verbose_name="포스터"),
        ),
    ]
