# Generated by Django 5.1 on 2024-08-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movies_post_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movies_post",
            old_name="Country",
            new_name="country",
        ),
    ]
