# Generated by Django 5.1 on 2024-08-28 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_rename_gnere_movies_post_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movies_post",
            name="famousline",
        ),
        migrations.CreateModel(
            name="FamousLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english", models.CharField(max_length=300, verbose_name="영어")),
                ("korean", models.CharField(max_length=100, verbose_name="한국어")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movies_post",
                        verbose_name="영화",
                    ),
                ),
            ],
        ),
    ]
