# Generated by Django 5.1 on 2024-08-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_remove_movies_post_famousline_famousline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="famousline",
            name="movie",
        ),
        migrations.AlterField(
            model_name="famousline",
            name="korean",
            field=models.CharField(max_length=150, verbose_name="한국어"),
        ),
    ]
